### ISSUE TITLE
Testing: topic model feature

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-TextAnalysis#8] opened 2017-05-23 20:06 UTC
The [topic-model](https://github.com/omeka/plugin-TextAnalysis/tree/topic-model) branch introduces topic modeling as a selectable feature when analyzing a corpus. You'll need to [download and install MALLET](http://mallet.cs.umass.edu/download.php) and enter the path (from root) to the directory containing the MALLET executable. You'll also need to make the `TextAnalysis\mallet_tmp` directory writable by the web server.

Once these steps are done, and the plugin configuration page shows no warnings, just analyze a corpus as usual, selecting the "Topic Model (MALLET)" feature. After the process is complete you should see "Topic Model" results on the analysis pages.

**Comment by mebrett** [comment] 2017-05-24 13:38
To clarify: install mallet on the server on which the Omeka installation is running? On the same directory level as the installation, or just somewhere on that server?

**Comment by jimsafley** [comment] 2017-05-24 14:01
Install MALLET _anywhere_ on the server and, in the TextAnalysis configuration page, point to the directory where the executable is, e.g. /path/to/mallet/bin

**Comment by jimsafley** [comment] 2017-05-24 14:02
You'll also need to make the TextAnalysis/mallet_tmp directory writable by the web server.

**Comment by mebrett** [comment] 2017-05-24 17:11
We've resolved with issue with the php extension and I've double-checked that the mallet folder is writable, etc. However, I'm still getting a [not available] for the analysis once the process is complete.

![screen shot 2017-05-24 at 1 10 45 pm](https://cloud.githubusercontent.com/assets/2314070/26416020/7f1f7df6-4082-11e7-803e-4fde4c31f86e.png)

thoughts?

**Comment by mebrett** [comment] 2017-05-24 21:06
Latest commit allows me to access the Mallet analysis. For corpora with a sequencing element, I get a dropdown to see the analysis for each sequence (in my case, years). If I run a corpora without a sequencing element, I get analysis for the whole corpora
<img width="1019" alt="screen shot 2017-05-24 at 5 05 28 pm" src="https://cloud.githubusercontent.com/assets/2314070/26425566/3a75b9ba-40a3-11e7-946b-f09b72d75006.png">

If we have time, I'd like @alyssafahringer to take a look at this next week, in case I've missed anything.

**Comment by jimsafley** [comment] 2017-05-25 14:28
Users can now add extra stopwords for the "Topic Model" feature. These are in addition to common English stopwords, which are omitted by default. This feature needs to be tested.

**Comment by mebrett** [comment] 2017-05-25 16:27
I can confirm that stop words are removed from the models, and that it takes lists and other whitespace separated formats.

**Comment by jimsafley** [comment] 2017-05-26 14:19
Users can no longer analyze a corpus when there are no analysis features available (i.e. when NLU and Mallet aren't configured). Similarly, the analyze page should only show the features that are available with regard to configuration. I've also changed the copy on the various pages to be more clear. Please test the changes and proof the copy.

**Comment by mebrett** [comment] 2017-05-30 16:49
I appreciate the "cannot use features when no credentials" function. One question - the lede for the config page text says "Analyze corpora that were created using the the Ngram plugin." but I am still seeing the functionality to use the Watson/Bluemix to analyze elements on the item level - is this going to remain part of the plugin, just less important?

**Comment by jimsafley** [comment] 2017-05-30 16:54
Yes, I don't think we should remove that feature. I'll add more text to the config page to make this clear.

**Comment by alyssafahringer** [comment] 2017-06-01 17:53
A few questions/comments about user experience. Let me preface this by saying I do not have extensive experience with topic modeling, so some of these questions might be due to my lack of knowledge about the method.  

I'm testing this on [Megan's install](http://dev.omeka.org/mebrett/Omeka/admin/). 

![screen shot 2017-06-01 at 13 31 00](https://cloud.githubusercontent.com/assets/8807816/26692504/f527e856-46ce-11e7-8ba6-9e5887332a90.png)

- On the analyze corpus page, should there be more options other than just topic model (MALLET) under features? I'm thinking of the features you see listed for NLU, such as entities, keywords, categories, and concepts. 
- Some of the helper text on the analyze corpus page uses NLU, while other helper text uses "NLU." 
- Under stopwords on the analyze corpus page, the helper text reads "In addition to common English stopwords"--would we be able to have a list of the words already excluded? If not on that page itself, than perhaps in the documentation? 

![screen shot 2017-06-01 at 13 38 22](https://cloud.githubusercontent.com/assets/8807816/26692696/9f05fca0-46cf-11e7-95c9-307febbcabb4.png)

After selecting a year for analysis, I have some questions about the way results are displayed: 
- It seems that for each year, regardless of the amount of items within the corpus for that selected year, it spits out 10 topics (so, hypothetically, if I had 50 items that listed 1813 as the year, but only 5 items for 1812, I would still get 10 topics for both years). Is that typical for topic modeling? 
- What does the percentage mean? It might be helpful to have helper text on the page to describe what that percentage denotes. 
- Does there have to be a line graph? Similarly, are these results exportable? If they are, then it would make sense to have a graph because then users could manipulate the results and the way those results are displayed. Or could the results for each year be graphed in a different way on that page? 

For the years [1813](http://dev.omeka.org/mebrett/Omeka/admin/text-analysis/corpora/topic-model?id=16&sequence_member=1813), [1817](http://dev.omeka.org/mebrett/Omeka/admin/text-analysis/corpora/topic-model?id=16&sequence_member=1817), and [1818](http://dev.omeka.org/mebrett/Omeka/admin/text-analysis/corpora/topic-model?id=16&sequence_member=1818) of the results of the topic model for [this corpus](http://dev.omeka.org/mebrett/Omeka/admin/ngram/corpora/show/id/9), the percentages listed for topics add up to 99, instead of 100. Is that expected behavior?

**Comment by jimsafley** [comment] 2017-06-01 18:44
1. Features that cannot be run aren't listed. For NLU features, you must have configured a Bluemix username and password.
1. "NLU" and "Topic Model" are in quotes because they reference specific features, which are labeled as such.
1. The stoplist can be found here: https://github.com/mimno/Mallet/blob/master/stoplists/en.txt
1. Yes, the algorithm generates a total of 10 topics for the _entire_ corpus, and assigns each topic a percentage for every sequence.
1. "Percentage" is the percentage of the sequence assigned to a given topic. It's probably best to see it as how relevant each topic is to the sequence.
1. No, the interface does not have to have line graphs. I put them there nevertheless to help users visualize the percentage. The results aren't explorable at the sequence level.
1. They add up to 99 because I'm rounding percentages to the nearest whole number.

**Closed as completed** 2017-06-14 17:29 UTC
